version: '3.4'

services:
  #my-rentals.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #    - "ConnectionStrings:RentsCoreDbConnectionString=Host=rentscoredb;Database=RentsCoreDB;Username=admin;Password=admin1234"  
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
       - PGADMIN_DEFAULT_EMAIL=gustavojordao2@hotmail.com
       - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
       - "5050:80"
    volumes:
       - pgadmin_data:/root/.pgadmin

  rentscoredb:
    container_name: rentscoredb
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=RentsCoreDB
        - TZ:'UTC'
        - PGTZ:'UTC'
    restart: always
    ports:
       - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data/ 